### ISSUE TITLE
num_classes =150

### ISSUE THREAD

**Issue by urgonguyen** [RomRoc/deeplab_retrain_ade20k_colab#2]
I think num_classes= 151 like in this https://github.com/tensorflow/models/blob/master/research/deeplab/datasets/segmentation_dataset.py
`_ADE20K_INFORMATION = DatasetDescriptor(
    splits_to_sizes={
        'train': 20210,  # num of samples in images/training
        'val': 2000,  # num of samples in images/validation
    },
    num_classes=151,
    ignore_label=0,
)`

**Comment by RomRoc** [comment]
Yes thanks, I updated in the last version.
